version: '3'

services:
  api:
    image: shadrus/swarmlesssonapi:0.3
    ports:
      - 8090:80
    environment:
      - version=0.2      
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    secrets:
      - swarm-lessons-token
    logging:
      driver: json-file
      options:
        'max-size': '10m'
        'max-file': '5'

secrets:
  swarm-lessons-token:
    external: true